//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phim()
        {
            this.CtDonHangs = new HashSet<CtDonHang>();
        }
    
        public string maPhim { get; set; }
        public string tenPhim { get; set; }
        public string hinhDD { get; set; }
        public string hinhDD2 { get; set; }
        public string ndTomTat { get; set; }
        public Nullable<System.DateTime> ngayDang { get; set; }
        public int maLoai { get; set; }
        public string noiDung { get; set; }
        public string taiKhoan { get; set; }
        public Nullable<bool> daDuyet { get; set; }
        public string soTap { get; set; }
        public Nullable<int> giaBan { get; set; }
        public Nullable<int> giamGia { get; set; }
        public string nhaSanXuat { get; set; }
        public Nullable<int> luotMua { get; set; }
        public Nullable<System.DateTime> ngayPH { get; set; }
        public string doPG { get; set; }
        public string thoiLuong { get; set; }
        public string diemImdb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtDonHang> CtDonHangs { get; set; }
        public virtual LoaiPhim LoaiPhim { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
    }
}
